# Generated by Django 4.2.15 on 2025-04-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='unknown@faculty.com', max_length=254),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(default='unknown_faculty', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='cell_no',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='unknown@staff.com', max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='unknown@student.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='cell_no',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='unknown_staff', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cell_no',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='unknown_student', max_length=50, unique=True),
        ),
    ]
