# Generated by Django 4.2.15 on 2025-04-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_faculty_groups_faculty_is_active_faculty_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('BSCS', 'BSCS'), ('BSIT', 'BSIT'), ('BSSE', 'BSSE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('BSCS', 'BSCS'), ('BSIT', 'BSIT'), ('BSSE', 'BSSE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('BSCS', 'BSCS'), ('BSIT', 'BSIT'), ('BSSE', 'BSSE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
